### ISSUE TITLE
直接返回string类型的数据问题

### ISSUE THREAD

**Issue by ayun-alex** [galaxy-sea/galaxy-blogs#3]
你好，我这边按照你的方法写了对应的增强处理，如果返回是对象之类的没有问题，但是中间有返回一个String对象。发现进行StringHttpMessageConverter进行conver时发生了错误，提示是不能将一个对象转换为String类型。错误如下图：
![image](https://user-images.githubusercontent.com/25189339/98782499-0c1b9b80-2433-11eb-82f2-d6aa77505a8f.png)

**Comment by galaxy-sea** [comment]
已更新， 目前采用解决方案二，删除spring的StringHttpMessageConverter
解决方案1:  https://github.com/galaxy-sea/galaxy-blogs/commit/a4a0c14c0b909de2120c99034af3258f94c1ee27#diff-12170108cbeb77f8a2e9e4797e7dbbf4a4f0e215020423f2b498f1150ff608ea
解决方案2: https://github.com/galaxy-sea/galaxy-blogs/commit/6a4dffd62e83414905f4f90e745882b308d35e98#diff-12170108cbeb77f8a2e9e4797e7dbbf4a4f0e215020423f2b498f1150ff608ea

**Comment by galaxy-sea** [comment]
代码已经提交，目前不知道删除StringHttpMessageConverter会对@ResponseBody产生什么影响

**Comment by ayun-alex** [comment]
采用方案二已经可以了，先这样用着了，大佬流弊。

**Comment by galaxy-sea** [comment]
后续会先Spring团队提issues，这的确是坑
